# Generated by Django 4.0.5 on 2022-06-20 21:45

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('tel_no', models.IntegerField(blank=True, null=True)),
                ('email_f', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('account_ref', models.TextField(blank=True, max_length=254)),
                ('account_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('facility', models.ManyToManyField(related_name='accounts', to='tabasamapp.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('withdrawal', 'widhdrawal'), ('deposit', 'deposit')], max_length=45)),
                ('time_made', models.DateTimeField(auto_now_add=True)),
                ('transaction_code', models.CharField(max_length=254)),
                ('amount', models.FloatField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabasamapp.facility')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tabasamapp.accountstatement')),
            ],
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tabasamapp.facility'),
        ),
        migrations.AddField(
            model_name='accountstatement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to=settings.AUTH_USER_MODEL),
        ),
    ]
