# Generated by Django 4.0.5 on 2022-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabasamapp', '0004_alter_transaction_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('withdrawal', 'withdrawal'), ('deposit', 'deposit')], max_length=45),
        ),
    ]
