# Generated by Django 4.0.5 on 2022-06-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabasamapp', '0007_alter_transaction_transaction_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
