# Generated by Django 4.0.5 on 2022-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabasamapp', '0009_alter_transaction_maker_alter_transaction_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
